

def create_or_update_by_name  (options)
  ct = CaseType.find_by_name(options[:name])
  if ct.nil?
    ct = CaseType.create!(options)
  else
    ct.update!(options)
  end
  ct
end

create_or_update_by_name(name:                       'Appeal against conviction',
                            is_fixed_fee:            true,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     false,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'FXACV',
                            )
create_or_update_by_name(name:                      'Appeal against sentence',
                            is_fixed_fee:           true,
                            requires_cracked_dates: false,
                            requires_trial_dates:   false,
                            requires_retrial_dates: false,
                            allow_pcmh_fee_type:    false,
                            roles:                  %w(agfs lgfs),
                            fee_type_code:          'FXASE',
                            )
create_or_update_by_name(name:                       'Breach of Crown Court order',
                            is_fixed_fee:            true,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     false,
                            requires_maat_reference: false,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'FXCBR',
                            )
create_or_update_by_name(name:                       'Committal for Sentence',
                            is_fixed_fee:            true,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     false,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'FXCSE',
                            )
create_or_update_by_name(name:                       'Contempt',
                            is_fixed_fee:            true,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     false,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'FXCON',
                            )
create_or_update_by_name(name:                       'Cracked Trial',
                            is_fixed_fee:            false,
                            requires_cracked_dates:  true,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     true,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'GRRAK',
                            )
create_or_update_by_name(name:                       'Cracked before retrial',
                            is_fixed_fee:            false,
                            requires_cracked_dates:  true,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     true,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'GRCBR',
                            )
create_or_update_by_name(name:                       'Discontinuance',
                            is_fixed_fee:            false,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     true,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'GRDIS',
                            )
create_or_update_by_name(name:                       'Elected cases not proceeded',
                            is_fixed_fee:            true,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     false,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'FXENP',
                            )
create_or_update_by_name(name:                       'Guilty plea',
                            is_fixed_fee:            false,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    false,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     true,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs),
                            fee_type_code:           'GRGLT',
                            )
create_or_update_by_name(name:                       'Retrial',
                            is_fixed_fee:            false,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    true,
                            requires_retrial_dates:  true,
                            allow_pcmh_fee_type:     true,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs interim),
                            fee_type_code:           'GRRTR',
                            )
create_or_update_by_name(name:                       'Trial',
                            is_fixed_fee:            false,
                            requires_cracked_dates:  false,
                            requires_trial_dates:    true,
                            requires_retrial_dates:  false,
                            allow_pcmh_fee_type:     true,
                            requires_maat_reference: true,
                            roles:                   %w(agfs lgfs interim),
                            fee_type_code:           'GRTRL',
                            )

create_or_update_by_name(name: 'Hearing subsequent to sentence',
                            is_fixed_fee:             true,
                            requires_cracked_dates:   false,
                            requires_trial_dates:     false,
                            requires_retrial_dates:   false,
                            allow_pcmh_fee_type:      false,
                            requires_maat_reference:  true,
                            roles:                    ['lgfs'],
                            fee_type_code:            'FXH2S',
                            )

# create_or_update_by_name(name: 'Transfer',
#                             is_fixed_fee:             false,
#                             requires_cracked_dates:   false,
#                             requires_trial_dates:     false,
#                             requires_retrial_dates:   false,
#                             allow_pcmh_fee_type:      false,
#                             requires_maat_reference:  true,
#                             roles:                    ['lgfs'],
#                             )
#
# create_or_update_by_name(name: 'Warrant claim',
#                             is_fixed_fee:             false,
#                             requires_cracked_dates:   false,
#                             requires_trial_dates:     false,
#                             requires_retrial_dates:   false,
#                             allow_pcmh_fee_type:      false,
#                             requires_maat_reference:  true,
#                             roles:                    ['lgfs'],
#                             )
