[
  'Accident reconstruction report',
  'Accounts',
  'Computer experts',
  'Consultant medical reports',
  'Costs judge application fee',
  'Costs judge preparation award',
  'DNA testing',
  'Engineer',
  'Enquiry agents',
  'Facial mapping expert',
  'Financial expert',
  'Fingerprint expert',
  'Fire assessor/explosives expert',
  'Forensic scientists',
  'Handwriting expert',
  'Interpreter',
  'Lip readers',
  'Medical expert',
  'Memorandum of conviction fee',
  'Meteorologist',
  'Other',
  'Overnight expenses',
  'Pathologist',
  'Photocopying',
  'Psychiatric reports',
  'Psychological report',
  'Surveyor/architect',
  'Transcripts',
  'Translator',
  'Travel costs',
  'Vet report',
  'Voice recognition',
].each do |disbursement_type_name|
  DisbursementType.find_or_create_by!(name: disbursement_type_name)
end
