DocumentType.find_or_create_by(description: 'The front sheet(s) from the commital bundle')
DocumentType.find_or_create_by(description: 'A copy of the indictment')
DocumentType.find_or_create_by(description: 'Order in respect of Judicial appointment')
DocumentType.find_or_create_by(description: 'Invoices/receipts for accomodation and travel expenses')
DocumentType.find_or_create_by(description: 'Hardship supporting evidence')
DocumentType.find_or_create_by(description: 'Details of any and all fee advancements made previously')
DocumentType.find_or_create_by(description: 'Other supporting evidence. A list of acceptable evidence')
DocumentType.find_or_create_by(description: 'Supporting evidence deemed unsuitable for summary trial')
DocumentType.find_or_create_by(description: 'Other/misc')
