DocumentType.find_or_create_by(description: 'Representation Order')
DocumentType.find_or_create_by(description: 'LAC1 - memo of conviction')
DocumentType.find_or_create_by(description: 'The front sheet(s) from the commital bundle')
DocumentType.find_or_create_by(description: 'A copy of the indictment')
DocumentType.find_or_create_by(description: 'Order in respect of Judicial appointment')
DocumentType.find_or_create_by(description: 'Invoices/receipts for accomodation and travel expenses')
DocumentType.find_or_create_by(description: 'Hardship supporting evidence')
DocumentType.find_or_create_by(description: 'Details of any and all fee advancements made previously')
DocumentType.find_or_create_by(description: 'Other supporting evidence/misc. A list of acceptable evidence')
DocumentType.find_or_create_by(description: 'Written justification if claim submitted more than 3 months after case concludes')
