EvidenceListItem.find_or_create_by(description: 'Representation Order', item_order: 1)
EvidenceListItem.find_or_create_by(description: 'LAC1 - memo of conviction', item_order: 2)
EvidenceListItem.find_or_create_by(description: 'The front sheet(s) from the commital bundle', item_order: 3)
EvidenceListItem.find_or_create_by(description: 'A copy of the indictment', item_order: 4)
EvidenceListItem.find_or_create_by(description: 'Order in respect of Judicial appointment', item_order: 5)
EvidenceListItem.find_or_create_by(description: 'Invoices/receipts for accomodation and travel expenses', item_order: 6)
EvidenceListItem.find_or_create_by(description: 'Hardship supporting evidence', item_order: 7)
EvidenceListItem.find_or_create_by(description: 'Details of any and all fee advancements made previously', item_order: 8)
EvidenceListItem.find_or_create_by(description: 'Other supporting evidence/misc. A list of acceptable evidence', item_order: 9)
EvidenceListItem.find_or_create_by(description: 'Written justification if claim submitted more than 3 months after case concludes', item_order: 10)
