languages:
  Ruby: true
  JavaScript: false
  PHP: true
  Python: true
exclude_paths:
- "app/interfaces/api/v1/*"
- "lib/demo_data/*"
- "db/*"
- "db/migrate/*"
- "db/seeds/*"
- "features/support/*"
- "script/*"
- "Gemfile*"
