version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 100
  similar-code:
    enabled: true
    config:
      threshold: 25
  identical-code:
    enabled: true
    config:
      threshold: 18
  method-count:
    config:
      threshold: 24
plugins:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          filters:
            - "(call _ expose ___)" # exlude expose methods
  rubocop:
    enabled: true
    channel: rubocop-0-76
    config:
      file: .rubocop.yml
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
exclude_patterns: # customize
- .bundle/
- app/assets/fonts/
- app/assets/images/
- "**/vendor/"
- bin/rails
- bin/rake
- doc/
- files/
- public/
- spec/
- features/
- old_features/
- tmp/
- spikes/
- app/interfaces/api/v1/*
- lib/demo_data/*
- db/*
- db/migrate/*
- db/seeds/*
- features/support/*
- script/*
- Gemfile*
- scheduled_tasks/*_task.rb
