version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 100
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-50
    config:
      file: .rubocop.yml
  duplication:
    enabled: true
    config:
      languages:
        JavaScript: false
        PHP: true
        Python: true
        ruby:
          mass_threshold: 18
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
exclude_patterns: # customize
- .bundle/
- app/assets/fonts/
- app/assets/images/
- app/assets/javascripts/vendor/
- app/assets/stylesheets/vendor/
- "**/vendor/"
- bin/rails
- bin/rake
- doc/
- files/
- public/
- spec/
- features/
- old_features/
- tmp/
- spikes/
- app/interfaces/api/entities/*
- app/interfaces/api/v1/*
- lib/demo_data/*
- db/*
- db/migrate/*
- db/seeds/*
- features/support/*
- script/*
- Gemfile*
- scheduled_tasks/*_task.rb
