plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/demo_data/**/*'
    - 'lib/tasks/**/*'
    - 'features/**/*'
    - 'node_modules/**/*'
    - 'old_features/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'storage/**/*'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\A|\s)#','.*\s+ # .*']
  AllowHeredoc: true

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]

Metrics/BlockLength:
  AllowedMethods:
    - included
    - class_methods
    - namespace
    - expose
    - helpers
    - group
    - state_machine
    - resource
    - context
    - describe
    - let
    - it
    - specify
    - fcontext
    - fdescribe
    - fit
    - fspecify
    - configure
    - shared_examples
    - shared_context
    - shared_examples_for
    - factory
    - trait
    - define

Naming/VariableNumber:
  AllowedPatterns: ['_scheme_[0-9]{1,2}$']

Rails/FilePath:
  EnforcedStyle: arguments

Rails/SquishedSQLHeredocs:
  Enabled: false

RSpec:
  Language:
    Expectations:
      - expect_claim_and_all_associations_to_be_gone
      - expect_claim_and_all_associations_to_be_present
      - expect_error_response
      - expect_invalid_attribute_with_message
      - expect_unauthorised_error
      - expect_valid_attribute
      - expect_validate_success_response
      - expect_working_days
      - should_be_valid_if_equal_to_value
      - should_error_if_after_specified_date
      - should_error_if_after_specified_field
      - should_error_if_before_specified_date
      - should_error_if_earlier_than_earliest_repo_date
      - should_error_if_earlier_than_earliest_reporder_date
      - should_error_if_earlier_than_other_date
      - should_error_if_equal_to_value
      - should_error_if_exceeds_length
      - should_error_if_field_dates_match
      - should_error_if_in_future
      - should_error_if_later_than_other_date
      - should_error_if_not_present
      - should_error_if_present
      - should_error_if_too_far_in_the_past
      - should_error_with
      - should_not_error
      - valid_cclf_json?
    Includes:
      Examples:
        - it_returns

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/StringConcatenation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/views/**/*
    - spec/requests/**/*
    - spec/api/v1/external_users/claims/integration/*
    # TODO: To fix
    - spec/validators/claim/advocate_interim_claim_web_validations_spec.rb
    - spec/validators/cracked_trial_validation_spec.rb
    - spec/api/posting_to_root_spec.rb
    - spec/models/claim/base_claim_spec.rb

inherit_from: .rubocop_todo.yml
