AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/demo_data/**/*'
    - 'lib/tasks/**/*'
    - 'features/**/*'
    - 'old_features/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - included
    - class_methods
    - namespace
    - expose
    - helpers
    - group
    - state_machine

Metrics/ModuleLength:
  Exclude:
    - 'app/models/claims/state_machine.rb'

inherit_from: .rubocop_todo.yml
