require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/demo_data/**/*'
    - 'lib/tasks/**/*'
    - 'features/**/*'
    - 'node_modules/**/*'
    - 'old_features/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'storage/**/*'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\A|\s)#','.*\s+ # .*']
  AllowHeredoc: true

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]

Metrics/BlockLength:
  AllowedMethods:
    - included
    - class_methods
    - namespace
    - expose
    - helpers
    - group
    - state_machine
    - resource
    - context
    - describe
    - let
    - it
    - specify
    - fcontext
    - fdescribe
    - fit
    - fspecify
    - configure
    - shared_examples
    - shared_context
    - shared_examples_for
    - factory
    - trait
    - define

Rails/FilePath:
  EnforcedStyle: arguments

Rails/SquishedSQLHeredocs:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/NestedGroups:
  Max: 4

Style/DateTime:
  AllowCoercion: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/StringConcatenation:
  Enabled: false

# Temporarily disable while fixing spec/* directory
Lint/RedundantCopDisableDirective:
  Enabled: false

inherit_from: .rubocop_todo.yml
