AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/demo_data/**/*'
    - 'lib/tasks/**/*'
    - 'features/**/*'
    - 'old_features/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#','.*\s+ # .*']
  AllowHeredoc: true

Metrics/BlockLength:
  ExcludedMethods:
    - included
    - class_methods
    - namespace
    - expose
    - helpers
    - group
    - state_machine
    - resource

Metrics/ModuleLength:
  Exclude:
    - 'app/models/claims/calculations.rb'
    - 'app/models/claims/state_machine.rb'
    - 'app/helpers/application_helper.rb'


Layout/EmptyLineAfterGuardClause:
  Enabled: false

inherit_from: .rubocop_todo.yml
