source 'https://rubygems.org'
ruby '2.5.1'
gem 'dotenv-rails', groups: [:development, :test]
gem 'active_model_serializers', '~> 0.10.7'
gem 'amoeba',                 '~> 3.1.0'
gem 'auto_strip_attributes',  '~> 2.4.0'
gem 'aws-sdk',                '~> 2'
gem 'awesome_print'
gem 'baby_squeel',            '~> 1.2.0'
gem 'cancancan',              '~> 1.15'
gem 'cocoon',                 '~> 1.2.6'
gem 'devise',                 '~> 4.4.3'
gem 'dropzonejs-rails',       '~> 0.8.2'
gem 'factory_bot_rails',      '~> 4.8.2'
gem 'faker',                  '~> 1.8.4'
gem 'gov_uk_date_fields',     '~> 3.0.0'
gem 'govuk_template',         '~> 0.23.1'
gem 'govuk_frontend_toolkit', '~> 7.4.1'
gem 'govuk_elements_rails',   '~> 3.1.2'
gem 'govuk_notify_rails',     '~> 2.0.0'
gem 'grape',                  '~> 1.0.2'
gem 'grape-entity',           '~> 0.7.1'
gem 'grape-papertrail',       '~> 0.1.2.1'
gem 'grape-swagger',          '~> 0.28.0'
gem 'grape-swagger-rails',    '~> 0.3.0'
gem 'haml-rails',             '~> 1.0.0'
gem 'hashie-forbidden_attributes', '>= 0.1.1'
gem 'jquery-rails',           '~> 4.3.1'
gem 'json-schema',            '~> 2.6.2'
gem 'nokogiri',               '~> 1.8'
gem 'kaminari',               '~> 0.17.0'
gem 'libreconv',              '~> 0.9.0'
gem 'logstasher',             '0.6.2'
gem 'logstuff',               '0.0.2'
gem 'newrelic_rpm',           '~> 5.1.0.344'
gem 'paperclip',              '~> 5.3.0'
gem 'paper_trail',            '~> 9.0.2'
gem 'pdf-forms'
gem 'pg',                     '~> 0.18.2'
gem 'rails',                  '>= 5.0.0', '< 5.1'
gem 'redis',                  '~> 3.3.1'
gem 'rubyzip'
gem 'config',                 '~> 1.2' # this gem provides our Settings.xxx mechanism
gem 'remotipart',             '~> 1.2'
gem 'rest-client',            '~> 2.0' # needed for scheduled smoke testing plus others
gem 'sass-rails',             '~> 5.0.7'
gem 'scheduler_daemon',       git: 'https://github.com/jalkoby/scheduler_daemon.git'
gem 'susy',                   '~> 2.2.14'
gem 'sentry-raven',           '~> 1.2.2'
gem 'simple_form',            '~> 4.0.0'
gem 'sprockets-rails',        '~> 3.2.1'
gem 'state_machine',          '~> 1.2.0'
gem 'state_machines-activerecord'
gem 'state_machines-audit_trail'
gem 'uglifier',                '>= 1.3.0'
gem 'zendesk_api'  ,           '1.12.1'
gem 'sidekiq',                 '~> 4.2.9'
gem 'utf8-cleaner',            '~> 0.2'
gem 'colorize'
gem 'shell-spinner', '~> 1.0', '>= 1.0.4'
gem 'ruby-progressbar'
gem 'geckoboard-ruby'
gem 'posix-spawn', '~> 0.3.13'

group :production, :devunicorn do
  gem 'rails_12factor', '0.0.3'
  gem 'unicorn-rails', '2.2.0'
  gem 'unicorn-worker-killer', '~> 0.4.4'
end

group :development, :devunicorn do
  gem 'meta_request'
  gem 'rubocop', '~> 0.50'
end

group :development, :devunicorn, :test do
  gem 'annotate'
  gem 'brakeman', :require => false
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'byebug'
  gem 'fuubar'
  gem 'guard-livereload',   '>= 2.5.2'
  gem 'listen',             '~> 2.10.0'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rack-livereload',    '~> 0.3.16'
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'puma'
  gem 'parallel_tests'
  gem 'site_prism'
  gem 'guard-jasmine',      '~> 2.0'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'guard-cucumber'
  gem 'net-ssh'
  gem 'net-scp'
end

group :test do
  gem 'capybara'
  gem 'climate_control'
  gem 'codeclimate-test-reporter',  require: false
  gem 'cucumber-rails',             require: false
  gem 'database_cleaner'
  gem 'json_spec'
  gem 'kaminari-rspec'
  gem 'launchy',                    '~> 2.4.3'
  gem 'poltergeist'
  gem 'rails-controller-testing'
  gem 'rspec-mocks'
  gem 'shoulda-matchers'
  gem 'selenium-webdriver'
  gem 'simplecov',                  require: false
  gem 'simplecov-csv',              require: false
  gem 'simplecov-multi',            require: false
  gem 'i18n-tasks'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
  gem 'hashdiff'
  gem 'test-prof'
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
