Clamby.configure({
  # check: false,
  # daemonize: true,
  config_file: Rails.root.join('config', 'clamd.container.conf'),
  # error_clamscan_missing: true,
  # error_clamscan_client_error: false,
  # error_file_missing: true,
  # error_file_virus: false,
  # fdpass: false,
  stream: true,
  # reload: false,
  # output_level: 'medium',
  # executable_path_clamscan: 'clamscan',
  # executable_path_clamdscan: 'clamdscan',
  # executable_path_freshclam: 'freshclam',
})