version: "3.2"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      CBO_BASE_DATABASE_USERNAME: "postgres"
      CBO_BASE_DATABASE_PASSWORD: "password"
      CBO_BASE_DATABASE_DATABASE: "cccd"
      SECRET_KEY_BASE: "fake"
      CBO_BASE_DATABASE_HOST: "database"
    depends_on:
      - database
    container_name: "cccd"

  database:
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: cccd
