apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ecr-delete-untagged-images-cronjob
  # currently the secret is only available in the cccd-dev namespace
  namespace: cccd-dev
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          restartPolicy: Never
          containers:
          - name: aws-cli
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cloud-platform/tools:awscli
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |-

                repo_name=laa-get-paid/cccd
                region=eu-west-2
                untagged_images=$( aws ecr list-images --region $region --repository-name $repo_name --filter "tagStatus=UNTAGGED" --query 'imageIds[*]' --output json)
                untagged_image_count=$(echo $untagged_images | jq length)

                if [ ${untagged_image_count} -gt 0 ]; then
                  echo "deleting $untagged_image_count images..."
                  aws ecr batch-delete-image --region $region --repository-name $repo_name --image-ids "$untagged_images" || true
                  echo "deleted!"
                else
                  echo "No untagged images to delete"
                fi

            env:
              - name: AWS_DEFAULT_REGION
                value: eu-west-2
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: cccd-ecr-credentials-output
                    key: access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: cccd-ecr-credentials-output
                    key: secret_access_key
