apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cccd-submitted-claims-report
spec:
  schedule: "5 3 * * 1"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 250000
      template:
        metadata:
          labels:
            tier: worker
        spec:
          restartPolicy: Never
          containers:
          - name: cronjob-worker
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-paid/cccd:app-latest
            imagePullPolicy: Always
            command:
              - rails
              - claims:submitted_claims_report
            envFrom:
            - configMapRef:
                name: cccd-app-config
            - secretRef:
                name: cccd-secrets
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cccd-rds
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: cccd-elasticache-redis
                  key: url
