# ARN will be suffixed with the host name of the environment, or 'local' if none
# List of possible hosts in file: lib/rails_host.rb
# Examples: 'cccd-claims-staging' or 'cccd-claims-local'
#
default: &default
  sns_arn: arn:aws:sns:eu-west-1:016649511486
  queues:
    - cccd-claims
  client_config:
    region: eu-west-1

production:
  <<: *default

development:
  <<: *default

devunicorn:
  <<: *default

test:
  <<: *default
