# For the Proof of Concept we are not taking into consideration the different envs we have,
# like dev, staging, api-sandbox, demo, etc. All of them will use the production URL.
#
default: &default
  client_config:
    timeout: 10
    open_timeout: 5

production:
  <<: *default
  endpoint: 'http://requestb.in/rcemvxrc' # These URLs only last 48h once created

development:
  <<: *default
  endpoint: 'http://requestb.in/1haud0l1' # These URLs only last 48h once created

devunicorn:
  <<: *default
  endpoint: ''

test:
  <<: *default
  endpoint: ''
