# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # old_secret_key_base: ee63f015ce225c840bf33a4f40e4890398221b394ca5f93e7ca6d4a491acf2f35bedcca677f146b22a6fa212099af990a16a80c7e8c8a8ac28927daa84e091a3
  secret_key_base: ce448bd7c975ec94f925bf2a24dee48427d11f2b81f5944b6dcc541f9d330dc0d60fda8fc1bb6e5c942b86f5a2726161d58cdaa8ebba3ab8088cd31c92094c55
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  survey_monkey_bearer_token: <%= ENV["SURVEY_MONKEY_BEARER_TOKEN"] %>

devunicorn:
  secret_key_base: ee63f015ce225c840bf33a4f40e4890398221b394ca5f93e7ca6d4a491acf2f35bedcca677f146b22a6fa212099af990a16a80c7e8c8a8ac28927daa84e091a3
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  survey_monkey_bearer_token: <%= ENV["SURVEY_MONKEY_BEARER_TOKEN"] %>

test:
  secret_key_base: 71bdb5d745e27e76e6df101da527598ae7586d2e9667e1a9a31111b3b71f7a63a23a6bab4e03b872a09fb3d26c9ade3006b7847825326148070a729317871add
  google_api_key: <%= ENV["GOOGLE_API_KEY"] || 'fake-google-api-key' %>
  survey_monkey_bearer_token: <%= ENV["SURVEY_MONKEY_BEARER_TOKEN"] || 'fake-survey-monkey-bearer-token' %>

# IMPORTANT Do not keep production secrets in the repository,
#           instead read values from the environment.
production:
  old_secret_key_base: <%= ENV["OLD_SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  survey_monkey_bearer_token: <%= ENV["SURVEY_MONKEY_BEARER_TOKEN"] %>
