---
:logfile: ./log/sidekiq.log
:queues:
  - [convert_document, 3]
  - [mailers, 3]
  - [default, 2]
  - [claims, 2]
  - [stats_reports, 1]
  - [active_storage_analysis, 1]
  - [active_storage_purge, 1]
:schedule:
  documents_canary:
    every: 120m
    class: DocumentCanaryJob
development:
  :verbose: true
  :concurrency: 5
production:
  :verbose: true
  :concurrency: 5
