---
:logfile: ./log/sidekiq.log
:queues:
  - [convert_document, 3]
  - [mailers, 3]
  - [default, 2]
  - [claims, 2]
  - [stats_reports, 1]
  - [active_storage_analysis, 1]
  - [active_storage_purge, 1]
development:
  :verbose: true
  :concurrency: 5
production:
  :verbose: true
  :concurrency: 5
:scheduler:
  :schedule:
    poll_injection_responses:
      cron: '0 * * * * *'
      class: Schedule::PollInjectionResponses
    document_cleaner:
      cron: '0 0 4 * * *'
      class: Schedule::DocumentCleaner
    agfs_management_information_generation:
      cron: '0 0 2 * * *'
      class: Schedule::AGFSManagementInformationGeneration
    agfs_management_information_v2_generation:
      cron: '0 50 1 * * *'
      class: Schedule::AGFSManagementInformationV2Generation
