apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: claim-for-crown-court-defence
  namespace: cccd-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cccd
    spec:
      containers:
        - name: cccd-app
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-paid/cccd:app-snsv9
          ports:
            - containerPort: 4567
#          livenessProbe:
#            httpGet:
#              path: /ping
#              port: 80
#          readinessProbe:
#            httpGet:
#              path: /healthcheck
#              port: 4567
          env:
            - name: RAILS_ENV
              value: 'production'
            - name: DB_PORT
              value: '5432'
            - name: DB_ENGINE
              value: 'postgres'
            - name: GRAPE_SWAGGER_ROOT_URL
              value: 'https://cccd-staging.apps.live-1.cloud-platform.service.justice.gov.uk'
            - name: GA_TRACKER_ID
              value: 'UA-37377084-48'
            - name: PDFTK_PATH
              value: '/usr/bin/pdftk'
            - name: SETTINGS__SLACK__BOT_NAME
              value: 'Injectotron'
            - name: SETTINGS__SLACK__FAIL_ICON
              value: ':katyperry:'
            - name: SETTINGS__SLACK__SUCCESS_ICON
              value: ':taytay:'
            - name: SETTINGS__AWS__POLL_MESSAGE_COUNT
              value: '1'
            - name: SETTINGS__AWS__POLL_MESSAGE_WAIT_TIME
              value: '10'
            - name: SETTINGS__AWS__S3__REGION
              value: 'eu-west-2'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cccd-rds
                  key: url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SECRET_KEY_BASE
            - name: CASE_WORKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: CASE_WORKER_PASSWORD
            - name: ADVOCATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: ADVOCATE_PASSWORD
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: ADMIN_PASSWORD
            - name: SUPERADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SUPERADMIN_USERNAME
            - name: SUPERADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SUPERADMIN_PASSWORD
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: AWS_ACCESS_KEY
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: AWS_REGION
            - name: SETTINGS__AWS__S3__ACCESS
              valueFrom:
                secretKeyRef:
                  name: cccd-s3-bucket
                  key: access_key_id
            - name: SETTINGS__AWS__S3__SECRET
              valueFrom:
                secretKeyRef:
                  name: cccd-s3-bucket
                  key: secret_access_key
            - name: SETTINGS__AWS__S3__BUCKET
              valueFrom:
                secretKeyRef:
                  name: cccd-s3-bucket
                  key: bucket_name
            - name: GECKOBOARD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: GECKOBOARD_TOKEN
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: GOOGLE_API_KEY
            - name: GECKOBOARD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: GECKOBOARD_API_KEY
            - name: LAA_FEE_CALCULATOR_HOST
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: LAA_FEE_CALCULATOR_HOST
            - name: NEWRELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: NEWRELIC_LICENSE_KEY
            - name: SETTINGS__SLACK__BOT_URL
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SETTINGS__SLACK__BOT_URL
            - name: SETTINGS__AWS__SNS__SUBMITTED_TOPIC_ARN
              valueFrom:
                secretKeyRef:
                  name: cccd-messaging
                  key: topic_arn
            - name: SETTINGS__AWS__SNS__ACCESS
              valueFrom:
                secretKeyRef:
                  name: cccd-messaging
                  key: access_key_id
            - name: SETTINGS__AWS__SNS__SECRET
              valueFrom:
                secretKeyRef:
                  name: cccd-messaging
                  key: secret_access_key
            - name: SETTINGS__AWS__SQS__RESPONSE_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: cccd-messaging
                  key: sqs_cccd_id
            - name: SETTINGS__GOVUK_NOTIFY__API_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SETTINGS__GOVUK_NOTIFY__API_KEY
            - name: SETTINGS__GOVUK_NOTIFY__TEMPLATES__MESSAGE_ADDED_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SETTINGS__GOVUK_NOTIFY__TEMPLATES__MESSAGE_ADDED_EMAIL
            - name: SETTINGS__GOVUK_NOTIFY__TEMPLATES__NEW_USER
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key:  SETTINGS__GOVUK_NOTIFY__TEMPLATES__NEW_USER
            - name: SETTINGS__GOVUK_NOTIFY__TEMPLATES__NEW_EXTERNAL_ADVOCATE_ADMIN
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SETTINGS__GOVUK_NOTIFY__TEMPLATES__NEW_EXTERNAL_ADVOCATE_ADMIN
            - name: SETTINGS__GOVUK_NOTIFY__TEMPLATES__NEW_EXTERNAL_LITIGATOR_ADMIN
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SETTINGS__GOVUK_NOTIFY__TEMPLATES__NEW_EXTERNAL_LITIGATOR_ADMIN
            - name: SETTINGS__GOVUK_NOTIFY__TEMPLATES__PASSWORD_RESET
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SETTINGS__GOVUK_NOTIFY__TEMPLATES__PASSWORD_RESET
            - name: SETTINGS__GOVUK_NOTIFY__TEMPLATES__UNLOCK_INSTRUCTIONS
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SETTINGS__GOVUK_NOTIFY__TEMPLATES__UNLOCK_INSTRUCTIONS
            - name: TEST_CHAMBER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: TEST_CHAMBER_API_KEY
            - name: ZENDESK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: ZENDESK_USERNAME
            - name: ZENDESK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: ZENDESK_TOKEN
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SENTRY_DSN
            - name: CCR_CASEWORKER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: CCR_CASEWORKER_API_KEY
            - name: CCLF_CASEWORKER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: CCLF_CASEWORKER_API_KEY

