apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    metadata:
      name: db-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: cccd-app
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-paid/cccd:app-latest
          command:
            - bundle
            - exec
            - rake
            - db:migrate
          env:
            - name: RAILS_ENV
              value: 'production'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cccd-rds
                  key: url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SECRET_KEY_BASE
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: AWS_REGION
