apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
spec:
  template:
    metadata:
      name: db-seed
    spec:
      restartPolicy: Never
      containers:
        - name: cccd-app
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-paid/cccd:app-latest
          command:
            - bundle
            - exec
            - rake
            - db:seed
          env:
            - name: RAILS_ENV
              value: 'production'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cccd-rds
                  key: url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SECRET_KEY_BASE
            - name: CASE_WORKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: CASE_WORKER_PASSWORD
            - name: ADVOCATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: ADVOCATE_PASSWORD
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: ADMIN_PASSWORD
            - name: SUPERADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SUPERADMIN_USERNAME
            - name: SUPERADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: SUPERADMIN_PASSWORD
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: AWS_REGION
            - name: TEST_CHAMBER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cccd-secrets
                  key: TEST_CHAMBER_API_KEY
