# These values will be used by VCR to make requests and record cassettes. DO NOT change them.
# If you need to re-record a cassette, start a server in this host/port with RAILS_ENV set to test.
#
# example:
# ```bash
# RAILS_ENV=test rails s -p 3001 -P /tmp/rails3001.pid
# ```
remote_api_key: 'not-provided'
remote_api_url: 'http://localhost:3001/api'
secret_key_base: 71bdb5d745e27e76e6df101da527598ae7586d2e9667e1a9a31111b3b71f7a63a23a6bab4e03b872a09fb3d26c9ade3006b7847825326148070a729317871add
